enableScripts: false

nodeLinker: node-modules

npmScopes:
  navikt:
    npmAlwaysAuth: true
    npmAuthToken: ghs_15368_eyJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJhdXRobmQiLCJjdHgiOiI1RHVjY2JPUWxlNWVza1BYb1F3WEw3Z1JGUk1ZcmlSODlvWnM0Ym5CVzlxNGpyUTdxUHRDbEpZIiwiZXhwIjoxNzg5NDYwNDYxLCJpYXQiOjE3ODk0NTY4NjEsImlzcyI6ImdpdGh1YiIsImp0aSI6IjI1MjI2MzA3LWJjMDAtNGIyZS1hNTUzLWU5NTcwN2ZjMzlmNyIsInZlciI6M30.P0QEdzKekSWq21rWZGK9_B3ROIP5mmrSBlIeEoyMz5HZdozm9yNbD5PUqPMEens0dsPzRW-eaJcSesv4iDkywA
    npmRegistryServer: "https://npm.pkg.github.com"

yarnPath: .yarn/releases/yarn-4.12.0.cjs
