enableScripts: false

nodeLinker: node-modules

npmScopes:
  navikt:
    npmAlwaysAuth: true
    npmAuthToken: ghs_15368_eyJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJhdXRobmQiLCJjdHgiOiJQR1RWdWYzSVRERjJSTDM1T3pqZ1k0M01zR0ozN2tuZGJiVE5KX1daRGo3QlhJcmU0Vi1LSTVRIiwiZXhwIjoxNzg5MTIxODQ4LCJpYXQiOjE3ODkxMTgyNDgsImlzcyI6ImdpdGh1YiIsImp0aSI6IjJhYzcyYjE5LWEzMjYtNGMwNS1hNmZhLTAyYjY1Njg3MDdiZCIsInZlciI6M30.wg3W9ucD98XRRAu4NUb0tBh7t-whfK2wajV_NBnnZy2YS6g3wd8KZ2Za_vOuzE67t2U0gHQQozAn2Vj6VhEaIQ
    npmRegistryServer: "https://npm.pkg.github.com"

yarnPath: .yarn/releases/yarn-4.12.0.cjs
