name: "verify: server"

on:
  pull_request:
    branches:
      - "**"
    paths:
      - "server/**"
      - ".github/workflows/verify-server.yml"

defaults:
  run:
    working-directory: server

jobs:
  verify:
    name: Verify there are no lint or typescript errors
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # ratchet:actions/checkout@v7
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # ratchet:actions/setup-node@v7.0.0
        with:
          node-version: "22"
          registry-url: https://npm.pkg.github.com/
          scope: "@navikt"

      - name: Configure Yarn for GitHub Packages
        uses: ./.github/actions/configure-yarn
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies
        run: yarn install --immutable

      - name: Run ESLint
        run: yarn lint

      - name: Check for typescript errors
        run: yarn check:types
